apiVersion: apps/v1
kind: Deployment
metadata:
  name: predictor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: predictor
  template:
    metadata:
      labels:
        app: predictor
    spec:
      containers:
        - name: predictor
          image: predictor:v0.2
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          env:
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: predictor-config
                  key: LOG_LEVEL

          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3